"""
Insight Generator
Generates actionable insights from patterns, predictions, and opportunities.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional
import logging
import uuid

from ..types import (
    DetectedPattern,
    NovelFailureMode,
    SuccessFormula,
    InnovationOpportunity,
    Prediction,
)


logger = logging.getLogger(__name__)


@dataclass
class Insight:
    """An actionable insight generated by PROPHET"""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    insight_type: str = ""  # pattern, failure, success, opportunity, prediction
    title: str = ""
    summary: str = ""
    details: str = ""

    # Impact and priority
    impact_score: Decimal = Decimal("0.0")
    priority: str = "medium"  # critical, high, medium, low
    urgency: str = "normal"  # immediate, urgent, normal, deferred

    # Evidence
    source_type: str = ""  # pattern, prediction, opportunity, etc.
    source_id: str = ""
    supporting_evidence: List[Dict[str, Any]] = field(default_factory=list)

    # Actions
    recommended_actions: List[str] = field(default_factory=list)
    affected_entities: List[str] = field(default_factory=list)

    # Metadata
    confidence: Decimal = Decimal("0.0")
    generated_at: datetime = field(default_factory=datetime.now)
    expires_at: Optional[datetime] = None

    # Status
    status: str = "new"  # new, acknowledged, in_progress, resolved, dismissed

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "id": self.id,
            "insight_type": self.insight_type,
            "title": self.title,
            "summary": self.summary,
            "details": self.details,
            "impact_score": float(self.impact_score),
            "priority": self.priority,
            "urgency": self.urgency,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "supporting_evidence": self.supporting_evidence,
            "recommended_actions": self.recommended_actions,
            "affected_entities": self.affected_entities,
            "confidence": float(self.confidence),
            "generated_at": self.generated_at.isoformat(),
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "status": self.status,
        }


class InsightGenerator:
    """
    Generates actionable insights from PROPHET's analysis.

    Insight types:
    - Pattern insights (from detected patterns)
    - Failure insights (from novel failure modes)
    - Success insights (from success formulas)
    - Opportunity insights (from innovation opportunities)
    - Prediction insights (from predictions)
    """

    def __init__(self):
        self._generated_insights: List[Insight] = []

    def generate_insights(
        self,
        patterns: List[DetectedPattern],
        novel_failures: List[NovelFailureMode],
        success_formulas: List[SuccessFormula],
        opportunities: List[InnovationOpportunity],
        predictions: List[Prediction],
    ) -> List[Insight]:
        """
        Generate insights from all PROPHET outputs.

        Args:
            patterns: Detected patterns
            novel_failures: Novel failure modes
            success_formulas: Success formulas
            opportunities: Innovation opportunities
            predictions: Predictions

        Returns:
            List of generated insights
        """
        insights = []

        # Pattern insights
        pattern_insights = self._generate_pattern_insights(patterns)
        insights.extend(pattern_insights)

        # Failure insights
        failure_insights = self._generate_failure_insights(novel_failures)
        insights.extend(failure_insights)

        # Success insights
        success_insights = self._generate_success_insights(success_formulas)
        insights.extend(success_insights)

        # Opportunity insights
        opportunity_insights = self._generate_opportunity_insights(opportunities)
        insights.extend(opportunity_insights)

        # Prediction insights
        prediction_insights = self._generate_prediction_insights(predictions)
        insights.extend(prediction_insights)

        # Sort by priority and impact
        insights.sort(key=lambda i: (
            {"critical": 4, "high": 3, "medium": 2, "low": 1}.get(i.priority, 0),
            float(i.impact_score)
        ), reverse=True)

        self._generated_insights.extend(insights)
        logger.info(f"Generated {len(insights)} insights")

        return insights

    def _generate_pattern_insights(
        self,
        patterns: List[DetectedPattern],
    ) -> List[Insight]:
        """Generate insights from detected patterns"""
        insights = []

        for pattern in patterns:
            if float(pattern.significance_score) < 0.5:
                continue

            insight = Insight(
                insight_type="pattern",
                title=f"Pattern Detected: {pattern.name}",
                summary=pattern.description,
                details=self._format_pattern_details(pattern),
                impact_score=pattern.significance_score,
                priority=self._determine_priority(float(pattern.significance_score)),
                urgency="normal",
                source_type="pattern",
                source_id=pattern.pattern_id,
                supporting_evidence=[pattern.evidence],
                recommended_actions=self._get_pattern_actions(pattern),
                confidence=pattern.confidence,
            )
            insights.append(insight)

        return insights

    def _generate_failure_insights(
        self,
        failures: List[NovelFailureMode],
    ) -> List[Insight]:
        """Generate insights from novel failure modes"""
        insights = []

        for failure in failures:
            urgency = "immediate" if failure.urgency.value == "critical" else "urgent"

            insight = Insight(
                insight_type="failure",
                title=f"Novel Failure Mode: {failure.proposed_name}",
                summary=(
                    f"New failure mode affecting {failure.affected_parts_count} parts "
                    f"with {failure.failure_count} occurrences"
                ),
                details=self._format_failure_details(failure),
                impact_score=failure.confidence_score,
                priority="high" if failure.urgency.value in ["critical", "high"] else "medium",
                urgency=urgency,
                source_type="novel_failure",
                source_id=failure.id,
                supporting_evidence=[failure.common_characteristics],
                recommended_actions=[
                    "Investigate root cause",
                    "Update failure taxonomy",
                    "Implement preventive measures",
                ],
                affected_entities=failure.affected_part_types,
                confidence=failure.confidence_score,
            )
            insights.append(insight)

        return insights

    def _generate_success_insights(
        self,
        formulas: List[SuccessFormula],
    ) -> List[Insight]:
        """Generate insights from success formulas"""
        insights = []

        for formula in formulas:
            if float(formula.success_rate) < 0.85:
                continue

            insight = Insight(
                insight_type="success",
                title=f"Success Pattern: {formula.name}",
                summary=(
                    f"Formula with {float(formula.success_rate):.0%} success rate "
                    f"in {formula.domain} domain"
                ),
                details=self._format_success_details(formula),
                impact_score=formula.success_rate,
                priority="medium",
                urgency="normal",
                source_type="success_formula",
                source_id=formula.id,
                supporting_evidence=[{
                    "required_parts": formula.required_parts,
                    "success_rate": float(formula.success_rate),
                    "sample_size": formula.sample_size,
                }],
                recommended_actions=[
                    f"Apply formula to {formula.domain} applications",
                    "Document and share best practices",
                    "Validate in similar domains",
                ],
                confidence=formula.confidence_score,
            )
            insights.append(insight)

        return insights

    def _generate_opportunity_insights(
        self,
        opportunities: List[InnovationOpportunity],
    ) -> List[Insight]:
        """Generate insights from innovation opportunities"""
        insights = []

        for opp in opportunities:
            if float(opp.priority_score) < 0.4:
                continue

            insight = Insight(
                insight_type="opportunity",
                title=f"Innovation Opportunity: {opp.title}",
                summary=opp.description,
                details=self._format_opportunity_details(opp),
                impact_score=opp.estimated_impact_score,
                priority=self._determine_priority(float(opp.priority_score)),
                urgency="normal",
                source_type="innovation_opportunity",
                source_id=opp.id,
                supporting_evidence=[{
                    "problem": opp.problem_statement,
                    "solution": opp.proposed_solution,
                    "market_size": opp.affected_market_size,
                }],
                recommended_actions=[
                    opp.proposed_solution,
                    "Conduct feasibility analysis",
                    "Develop proof of concept",
                ],
                confidence=opp.confidence,
            )
            insights.append(insight)

        return insights

    def _generate_prediction_insights(
        self,
        predictions: List[Prediction],
    ) -> List[Insight]:
        """Generate insights from predictions"""
        insights = []

        for pred in predictions:
            if float(pred.probability) < 0.5:
                continue

            pred_type = pred.prediction_type.value
            urgency = "urgent" if pred.timeline_days < 30 else "normal"

            insight = Insight(
                insight_type="prediction",
                title=f"Prediction: {pred_type.title()} for {pred.subject_id[:20]}",
                summary=(
                    f"{pred.probability:.0%} probability of {pred_type} "
                    f"within {pred.timeline_days} days"
                ),
                details=self._format_prediction_details(pred),
                impact_score=pred.probability,
                priority="high" if float(pred.probability) > 0.7 else "medium",
                urgency=urgency,
                source_type="prediction",
                source_id=pred.id,
                supporting_evidence=[pred.prediction],
                recommended_actions=pred.prevention_actions or [
                    "Monitor closely",
                    "Prepare contingency plan",
                ],
                affected_entities=[pred.subject_id],
                confidence=pred.confidence,
            )
            insights.append(insight)

        return insights

    def _format_pattern_details(self, pattern: DetectedPattern) -> str:
        """Format pattern details for insight"""
        return (
            f"Layer: {pattern.layer.name}\n"
            f"Type: {pattern.pattern_type}\n"
            f"Sample Size: {pattern.sample_size}\n"
            f"Detection Count: {pattern.detection_count}"
        )

    def _format_failure_details(self, failure: NovelFailureMode) -> str:
        """Format failure details for insight"""
        chars = failure.common_characteristics
        return (
            f"Category: {failure.proposed_category}\n"
            f"Affected Types: {', '.join(failure.affected_part_types[:5])}\n"
            f"Common Characteristics: {chars}\n"
            f"Urgency: {failure.urgency.value}"
        )

    def _format_success_details(self, formula: SuccessFormula) -> str:
        """Format success formula details for insight"""
        return (
            f"Domain: {formula.domain}\n"
            f"Success Rate: {float(formula.success_rate):.0%}\n"
            f"Average Lifespan: {formula.average_lifespan_hours} hours\n"
            f"Required Parts: {len(formula.required_parts)}\n"
            f"Sample Size: {formula.sample_size}"
        )

    def _format_opportunity_details(self, opp: InnovationOpportunity) -> str:
        """Format opportunity details for insight"""
        return (
            f"Type: {opp.opportunity_type.value}\n"
            f"Problem: {opp.problem_statement}\n"
            f"Solution: {opp.proposed_solution}\n"
            f"Market Size: {opp.affected_market_size:,}"
        )

    def _format_prediction_details(self, pred: Prediction) -> str:
        """Format prediction details for insight"""
        return (
            f"Subject: {pred.subject_id}\n"
            f"Probability: {float(pred.probability):.0%}\n"
            f"Timeline: {pred.timeline_days} days\n"
            f"Predicted Mode: {pred.predicted_failure_mode or 'N/A'}"
        )

    def _determine_priority(self, score: float) -> str:
        """Determine priority from score"""
        if score >= 0.8:
            return "critical"
        elif score >= 0.6:
            return "high"
        elif score >= 0.4:
            return "medium"
        else:
            return "low"

    def _get_pattern_actions(self, pattern: DetectedPattern) -> List[str]:
        """Get recommended actions for a pattern"""
        actions = []

        layer = pattern.layer.name

        if layer == "STATISTICAL":
            actions.append("Investigate statistical anomaly")
            actions.append("Monitor for trend continuation")
        elif layer == "BEHAVIORAL":
            actions.append("Document behavioral pattern")
            actions.append("Share with relevant teams")
        elif layer == "RELATIONAL":
            actions.append("Update compatibility database")
            actions.append("Review related assemblies")
        elif layer == "INNOVATION":
            actions.append("Evaluate innovation opportunity")
            actions.append("Conduct feasibility study")
        elif layer == "META":
            actions.append("Review system-wide implications")
            actions.append("Update strategic planning")

        return actions

    def get_insights_by_priority(
        self,
        priority: str,
    ) -> List[Insight]:
        """Get insights by priority level"""
        return [i for i in self._generated_insights if i.priority == priority]

    def get_actionable_insights(
        self,
        limit: int = 10,
    ) -> List[Insight]:
        """Get top actionable insights"""
        actionable = [
            i for i in self._generated_insights
            if i.recommended_actions and i.status == "new"
        ]
        return sorted(
            actionable,
            key=lambda i: float(i.impact_score),
            reverse=True
        )[:limit]

    def acknowledge_insight(self, insight_id: str) -> bool:
        """Mark an insight as acknowledged"""
        for insight in self._generated_insights:
            if insight.id == insight_id:
                insight.status = "acknowledged"
                return True
        return False

    def resolve_insight(self, insight_id: str) -> bool:
        """Mark an insight as resolved"""
        for insight in self._generated_insights:
            if insight.id == insight_id:
                insight.status = "resolved"
                return True
        return False
